name: Create alfred workflow

# Controls when the workflow will run
on:
  push:
    tags:
      - v*

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v3.0.0
      
      - name: Create the alfredworkflow zip file
        uses: TheDoctor0/zip-release@0.6.1
        with:
          filename: alfred-imessage-2fa-copy.alfredworkflow
          # optional, default is .
          path: .
          directory: .
          # List of excluded files / directories
          exclusions: '.github\* .git\* test*'
          type: zip

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "alfred-imessage-2fa-copy.alfredworkflow"
          bodyFile: "body.md"
          token: ${{ secrets.GITHUB_TOKEN }}
