name: Run tests

# Controls when the workflow will run
on:
  push:
    branch:
      - '*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v3.0.0
      
      - name: Run test
        run: ./test.sh

      - name: Report
        uses: dorny/test-reporter@v1.5.0
        with:
          path: test_results.xml
          reporter: java-junit
          fail-on-error: true